<Project Sdk="Microsoft.NET.Sdk">	
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<PackageProjectUrl>https://gruntapi.com</PackageProjectUrl>
		<RepositoryUrl>https://github.com/dend/grunt</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>halo,halo-api,api,halo-infinite,halo-mcc,halo-5,halo-wars,halo-4</PackageTags>
		<PackageIcon>grunt-logo.png</PackageIcon>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<TransformOnBuild>true</TransformOnBuild>
		<TransformOutOfDateOnly>false</TransformOutOfDateOnly>
		<Nullable>enable</Nullable>
		<AnalysisLevel>latest</AnalysisLevel>
		<PackageId>$(AssemblyName)</PackageId>
		<Authors>Den Delimarsky</Authors>
		<Company>Den Delimarsky</Company>
		<Product>$(AssemblyName)</Product>
		<Description>An unofficial wrapper for the Halo APIs. Currently supports the full API stack for Halo Infinite.</Description>
		<Copyright>2025 by Den Delimarsky</Copyright>
		<PackageReleaseNotes>Initial release of the Den.Dev.Grunt package.</PackageReleaseNotes>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<Version>0.0.0-local</Version>
		<Title>Den.Dev.Grunt</Title>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE" Pack="true" PackagePath="" />
	</ItemGroup>
	
	<ItemGroup>
	  <None Remove="stylecop.json" />
	</ItemGroup>
	
	<ItemGroup>
	  <AdditionalFiles Include="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\media\grunt-logo.png">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Den.Dev.Conch" Version="0.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.2" />
	  <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="endpoints.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>
</Project>
