// <copyright file="LobbyModule.cs" company="Den Delimarsky">
// Developed by Den Delimarsky.
// Den Delimarsky licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
// The underlying API powering Den.Dev.Grunt is managed by Halo Studios and Microsoft. This wrapper is not endorsed by Halo Studios or Microsoft.
// </copyright>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Den.Dev.Grunt.Core.Foundation;
using Den.Dev.Grunt.Endpoints;
using Den.Dev.Grunt.Models;
using Den.Dev.Grunt.Models.HaloInfinite;

namespace Den.Dev.Grunt.Core.Modules
{
    /// <summary>
    /// Module for lobby-related API operations including QoS servers and presence.
    /// </summary>
    public class LobbyModule : ModuleBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LobbyModule"/> class.
        /// </summary>
        /// <param name="client">The client instance to use for API requests.</param>
        internal LobbyModule(ClientBase client)
            : base(client, HaloCoreEndpoints.HaloInfiniteLobbyOrigin)
        {
        }

        /// <summary>
        /// Gets a list of available lobby servers.
        /// </summary>
        /// <returns>A list of Server instances if the request is successful. Otherwise, returns null.</returns>
        public async Task<HaloApiResultContainer<List<Server>, RawResponseContainer>> GetQosServers()
        {
            return await this.GetAsync<List<Server>>("/titles/hi/qosservers");
        }

        /// <summary>
        /// Gets the player presence status.
        /// </summary>
        /// <param name="presenceRequest">Presence request, containing a list of Xuids representing Xbox Live players.</param>
        /// <returns>If successful, an instance of <see cref="LobbyPresenceContainer"/> representing the lobby details. Otherwise, null.</returns>
        public async Task<HaloApiResultContainer<LobbyPresenceContainer, RawResponseContainer>> Presence(LobbyPresenceRequestContainer presenceRequest)
        {
            ArgumentNullException.ThrowIfNull(presenceRequest);

            return await this.GetAsync<LobbyPresenceContainer>("/hi/presence");
        }

        /// <summary>
        /// Gets a third-party join handle for a lobby.
        /// </summary>
        /// <param name="lobbyId">Unique lobby ID.</param>
        /// <param name="player">Player ID in the format of "xuid(XUID_VALUE)".</param>
        /// <param name="handleAudience">Audience for the join handle. Example value is "Friends".</param>
        /// <param name="handlePlatform">Platform for the join handle. Example value is "Discord".</param>
        /// <returns>An instance of LobbyJoinHandle if the request is successful. Otherwise, returns null.</returns>
        /// <remarks>It seems that this request requires a more "broad access" Spartan token that is generated by the game, and is not open to third-party apps. Additional investigation is required.</remarks>
        public async Task<HaloApiResultContainer<LobbyJoinHandle, RawResponseContainer>> ThirdPartyJoinHandle(string lobbyId, string player, string handleAudience, string handlePlatform)
        {
            return await this.GetAsyncFullUrl<LobbyJoinHandle>(
                $"https://{HaloCoreEndpoints.HaloInfiniteLobbyOrigin}.{HaloCoreEndpoints.ServiceDomain}/hi/lobbies/{lobbyId}/players/{player}/thirdPartyJoinHandle?audience={handleAudience}&platform={handlePlatform}",
                customHeaders: new List<KeyValuePair<string, string>>() { new KeyValuePair<string, string>("Accept-Language", "en-us") });
        }

        /// <summary>
        /// Bootstraps a new lobby.
        /// </summary>
        /// <param name="lobbyId">Unique lobby ID.</param>
        /// <param name="player">Player ID in the format of "xuid(XUID_VALUE)".</param>
        /// <param name="auth">Authentication to be used. "st" represents Spartan token.</param>
        /// <param name="lobbyBootstrapPayload">Binary payload (Bond-encoded) that contains the lobby bootstrap logic.</param>
        /// <returns>An instance of <see cref="JoinLobbyResponse"/> in the response container if successful. Otherwise, a null.</returns>
        public async Task<HaloApiResultContainer<JoinLobbyResponse, RawResponseContainer>> JoinLobby(string lobbyId, string player, string auth, byte[] lobbyBootstrapPayload)
        {
            return await this.Client.ExecuteAPIRequest<JoinLobbyResponse>(
                $"https://{HaloCoreEndpoints.HaloInfiniteLobbyOrigin}.{HaloCoreEndpoints.ServiceDomain}/hi/lobbies/{lobbyId}/players/{player}?auth={auth}",
                System.Net.Http.HttpMethod.Put,
                true,
                true,
                contentType: APIContentType.BondCompactBinary,
                binaryContent: lobbyBootstrapPayload,
                includeRawResponse: this.Client.IncludeRawResponses,
                enforceSuccess: false);
        }
    }
}
