name: Publish API Documentation

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - master
    paths:
      - 'docs/**'
      - 'Den.Dev.Grunt/Den.Dev.Grunt/Core/Modules/**'
      - 'Den.Dev.Grunt/Den.Dev.Grunt/APIDocsExamples/**'
      - 'Den.Dev.Grunt/Den.Dev.Grunt/Models/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Build Documentation
      run: docfx docs/docfx.json

    - name: Checkout compiled docs repo
      uses: actions/checkout@v4
      with:
        repository: 'dend/grunt-docs-compiled'
        path: '_compiled'
        token: ${{ secrets.DOCS_PAT }}

    - name: Deploy generated site
      run: |
        rm -rf _compiled/*
        cp -r docs/_site/* _compiled/

    - name: Commit and push
      working-directory: _compiled
      run: |
        git add -A
        git config user.name 'Den Delimarsky'
        git config user.email '1389609+dend@users.noreply.github.com'
        git commit -m "Docs update." || exit 0
        git push origin main
